services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/taskmanager
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data: