databases:
  - name: task-manager-db
    databaseName: taskmanager
    plan: free

services:
  - name: backend
    type: web
    env: docker
    plan: free # <-- Add this line
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: j2s5v8y/B?E(H+MbQeThWmZq4t7w9z$C
        sync: false

  - name: frontend
    type: web
    env: docker
    plan: free # <-- And add this line
    dockerfilePath: ./frontend/Dockerfile