databases:
  - name: task-manager-db
    databaseName: taskmanager
    plan: free

services:
  - name: backend
    type: web
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: task-manager-db
          property: connectionString

  - name: frontend
    type: web
    env: docker
    dockerfilePath: ./frontend/Dockerfile