services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: taskmanager-db
          property: connectionString
      - key: j2s5v8y/B?E(H+MbQeThWmZq4t7w9z$C
        sync: false

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerBuildArgs:
      - key: VITE_API_URL
        fromService:
          type: web
          name: backend
          property: url
          path: /api/

databases:
  - name: taskmanager-db
    plan: free