services:
  - name: mongodb
    type: pserv
    env: docker
    image:
      url: mongo:latest
    disk:
      name: mongo-data
      mountPath: /data/db
      sizeGB: 1

  - name: backend
    type: web
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        value: mongodb://mongodb:27017/taskmanager
      - key: JWT_SECRET
        sync: false

  - name: frontend
    type: web
    env: docker
    dockerfilePath: ./frontend/Dockerfile