databases:
  - name: taskmanager-db
    plan: free

services:
  - name: backend
    type: web
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile

  - name: frontend
    type: web
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile