databases:
  - name: taskmanager-db
    plan: free

services:
  - name: backend
    type: web
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: taskmanager-db
          property: connectionString
      - key: j2s5v8y/B?E(H+MbQeThWmZq4t7w9z$C
        sync: false